image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy
  - release

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar

release:
  stage: release
  release:
    name: CI Release $CI_COMMIT_SHORT_SHA
    assets:
    - name: BungeeServerManager.jar
      path: target/*.jar
