image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy
  - release

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar

release:
  stage: release
  only: tags
  script:
    - make changelog | tee release_changelog.txt
  release:
    name: My $CI_PROJECT_NAME Release 1.0-$CI_COMMIT_SHORT_SHA
    description: ./release_changelog.txt
    assets:
    - name: BungeeServerManager.jar
      path: target/*.jar
