#BungeeServerManager Configuration
ConfigVersion: 3

#Type here your MySQL Settings
MySQL:
  Host: Hostname
  Port: 3306 #Leave it, if you don't have anything else configured
  User: Username
  Database: Database
  Password: Password

#Settings for the Header in the Tablist
Header:
  SetHeader: false
  HeaderText: '&7Hello &4%player% &7you''re playing on server &a%server%'

#Settings for the Footer in the Tablist
Footer:
  SetFooter: false
  FooterText: '&7Hello &4%player% &7you''re playing on server &a%server%'

#Here you can change the appearance if the client pings the server in the multiplayer screen
ServerPing:
  SetMOTD: false
  OneMorePlayer: false
  MOTDText: 'Some text here'

#Here are some general plugin settings
General:
  HubCommands: hub;lobby
  AutoUpdater: true
  ForceServers: false
  EnableOnlineOfflineCheck: true
  OnlineOfflineCheckDelay: 10

#Here comes the language (I'm going to implement every message in the next few updates
Language:
  prefix: '&f[&4ServerManager&f]'
  NO_PERMISSION: "§cYou don't have permission to execute this command"
  SERVERS_LIST_HEADER: "§7The following servers are registered in the system§8:"
  ALL_SERVER_RELOAD_BROADCAST: "§7All servers have been reloaded by §4%PLAYER%"
  PREVIOUS_SERVER_DELETED_INFO: "§7The server you were previously on has been disabled! You have been connected to a lobby"
  SERVER_DELETED_BROADCAST: "§7The server %SERVER% §7has been deleted by §4%PLAYER%"
  SERVER_NOT_FOUND: "§7The server could not be found"
  SERVER_LIST_INFO: "§e%POSITION% §8- §7Name§8:§e %NAME% §7Status§8: %ISONLINE% §7Enabled§8: %ISENABLED% §7Lobby§8: %ISLOBBY% §7Restricted§8: %ISRESTRICTED% §7Displayname§8:§e %DISPLAYNAME% §7IP§8:§e %IP% §7Port§8:§e %PORT%"
  SERVER_RELOADED_BROADCAST: "§7The server %DISPLAYNAME% §7has been reloaded by §4%PLAYER%"
  SERVER_ENABLED_BROADCAST: "§7The server %DISPLAYNAME% §7has been enabled by §4%PLAYER%"
  SERVER_ALREADY_ENABLED: "§7This server is already enabled"
  SERVER_DISABLED_BROADCAST: "§7The server %DISPLAYNAME% §7has been disabled by §4%PLAYER%"
  PREVIOUS_SERVER_DISABLED: "§7The server you were previously on has been disabled! You have been connected to a lobby"
  SERVER_ALREADY_DISABLED: "§7This server is already disabled"
  SERVER_NOT_ACTIVE: "§7The server is not active"
  PREVIOUS_SERVER_EMPTIED: "§7The server you were previously on has been emptied by a staff member"
  GOTO_DESCRIPTION: "§e/goto <playername> §8- §7Connects you to the players current server"
  GOTO_PLAYER_NOT_ONLINE: "§cThe player §a%PLAYER% §cis not online"
  GOTO_CONNECTED: "§7You have been connected to §a%PLAYER%'s §7server"
  GOTO_ALREADY_ON_SERVER: "§cYou're already on §a%PLAYER%'s §cserver"
  ONLY_INGAME_COMMAND: "§cOnly ingame available"
  LOBBY_ALREADY_ON_LOBBY: "§cYou are already connected to a lobby"
  WHEREAMI_SERVER_INFO: "§7You're currently on the server§8: §e%SERVER%"
  WHEREAMI_CANNOT_FIND_SERVER: "§cCould not find your current server"