name: SpigotServerManager
main: ch.fetz.ServerManager.spigot.SpigotServerManager
author: Noah Fetz
version: 1.4.6
commands:
  servermanagerclient:
    usage: /servermanagerclient
    description: Opens the client-menu for BungeeServerManager
    permission: smc.use
    aliases: [smc]